name: JMH Performance Test
on: [push]
jobs:
  run-benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build and Run JMH
        run: |
          # 1. بناء المشروع وتوليد ملفات الـ Metadata
          mvn clean install -DskipTests -Drat.skip=true
          
          # 2. تشغيل الـ Benchmark باستخدام الكلاس المولد (Uber-jar)
          mvn exec:java "-Drat.skip=true" \
            "-Dexec.mainClass=org.openjdk.jmh.Main" \
            "-Dexec.args=-f 1 -wi 1 -i 1 .*MyBenchmark.*" \
            "-Dexec.classpathScope=test"
